#!/usr/bin/env bash
# Stop hook: stages and commits all working-tree changes at the end of
# every Claude Code turn, with a commit message generated by a nested
# `claude -p` call over the staged diff.
#
# Re-entrancy guard: the nested `claude -p` call is itself a Claude Code
# session in this same project and would otherwise fire this same Stop
# hook when IT stops, recursing. DEXXER_AUTOCOMMIT_RUNNING is exported so
# that nested invocation sees it and exits immediately.
set -uo pipefail

if [ -n "${DEXXER_AUTOCOMMIT_RUNNING:-}" ]; then
  exit 0
fi
export DEXXER_AUTOCOMMIT_RUNNING=1

cd "${CLAUDE_PROJECT_DIR:-$(pwd)}" || exit 0
git rev-parse --is-inside-work-tree >/dev/null 2>&1 || exit 0

git add -A
if git diff --cached --quiet; then
  exit 0
fi

DIFF="$(git diff --cached)"
MSG="$(printf '%s' "$DIFF" | claude -p \
  "Write ONE git commit message line (English, imperative mood, at most 72 characters, no surrounding quotes, no trailing period) summarizing the staged diff piped to you as input. Output only that single line and nothing else." \
  --model claude-haiku-4-5-20251001 2>/dev/null | head -n1 | tr -d '\r')"

if [ -z "$MSG" ]; then
  MSG="chore: auto-commit $(date -u +%Y-%m-%dT%H:%M:%SZ)"
fi

LOG=$(mktemp)
if git commit -m "$MSG" -m "Co-Authored-By: Claude Sonnet 5 <noreply@anthropic.com>" >"$LOG" 2>&1; then
  ESCAPED=$(printf '%s' "$MSG" | sed 's/\\/\\\\/g; s/"/\\"/g')
  printf '{"systemMessage": "Auto-committed: %s"}\n' "$ESCAPED"
else
  ESCAPED=$(sed 's/\\/\\\\/g; s/"/\\"/g' "$LOG" | tr '\n' ' ')
  printf '{"systemMessage": "Auto-commit FAILED: %s"}\n' "$ESCAPED"
fi
rm -f "$LOG"
