[toolchain]
anchor_version = "1.0.2"
solana_version = "3.1.9"
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
dexxer_core = "G2okX5Bae4CxfK8vzso1Ecc96QUv7E3P4YvxaZnaYXoV"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
