[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
dexxer_core = "Htuaqktaa4MkdBS3nbFcoRZuVdLHowZknpW35EokXXxT"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
