[package]
name = "dexxer_core"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "dexxer_core"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
idl-build = ["anchor-lang/idl-build"]

[dependencies]
anchor-lang = "=1.0.2"
ephemeral-rollups-sdk = { version = "0.16.2", features = ["anchor", "access-control"] }

[dev-dependencies]
proptest = "1.5"
