// app/scripts/gen-lwc.ts
//
// Inlines lightweight-charts' standalone production build into
// src/features/chart/lwcSource.generated.ts, so the chart's WebView page
// (`chartHtml.ts`) carries the library itself — no CDN fetch at runtime,
// works offline, and the pinned npm version is exactly what runs. The output
// is git-ignored (≈200 KB of minified JS) and rebuilt by `postinstall`, like
// patch-package; the version string makes a stale file visible in review.
//
// Run: npm run gen:lwc (from app/).
import { readFileSync, writeFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import { fileURLToPath } from 'node:url'
import path from 'node:path'

const here = path.dirname(fileURLToPath(import.meta.url))
const require = createRequire(import.meta.url)
const pkgDir = path.dirname(require.resolve('lightweight-charts/package.json'))
const version = (JSON.parse(readFileSync(path.join(pkgDir, 'package.json'), 'utf8')) as { version: string }).version
const source = readFileSync(path.join(pkgDir, 'dist/lightweight-charts.standalone.production.js'), 'utf8')
const outPath = path.join(here, '../src/features/chart/lwcSource.generated.ts')

writeFileSync(
  outPath,
  `// GENERATED by scripts/gen-lwc.ts from lightweight-charts@${version} (Apache-2.0) — do not edit.\n` +
    `export const LWC_VERSION = ${JSON.stringify(version)}\n` +
    `export const LWC_SOURCE = ${JSON.stringify(source)}\n`,
)
console.log(`gen-lwc: lightweight-charts@${version} -> ${path.relative(process.cwd(), outPath)}`)
